In [2]:
print("radha")

radha


In [3]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("placement_LR.csv")
X = df.iloc[:,0:1].values
y = df.iloc[:,-1].values
df.head()

In [31]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=2)

In [28]:
X_train.shape

(160, 1)

In [37]:
X_test[0:5]

array([[8.58],
       [7.15],
       [5.88],
       [6.22],
       [4.57]])

In [39]:
class MeraLR:
    def __init__(self):
        self.m = None
        self.b = None
    def fit(self , X_train , y_train):
        den = 0
        num = 0
        for i in range(X_train.shape[0]):
            num = num + (X_train[i] - np.mean(X_train))*(y_train[i] - np.mean(y_train))
            den = den + (X_train[i] - np.mean(X_train))**2
        self.m = num/den
        self.b = y_train.mean() - self.m * X_train.mean()
        print("m = " , self.m , "b = " , self.b)
    def predict(self , X_test):
        try:
            y_pred = self.m * X_test + self.b
            return y_pred
        except:
            print("Something went wrong while predicting.")
            return None

In [41]:
lr = MeraLR()
lr.fit(X_train , y_train)


m =  [0.55795197] b =  [-0.89611192]


In [43]:
y_pred = lr.predict(X_test)

In [45]:
from sklearn.metrics import r2_score
r2_score(y_test , y_pred)

0.7807301475103842

In [47]:
y_test[0]

np.float64(4.1)

In [49]:
X_test[0]

array([8.58])

In [50]:
lr.predict(X_test[0])

array([3.89111601])